services:
  - type: web
    name: time_horizon
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn time_horizon.wsgi:application
    plan: free
    autoDeploy: true
