# Generated by Django 4.2.2 on 2023-08-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
