# Generated by Django 4.2.4 on 2023-09-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_customuser_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
