# Generated by Django 4.2.4 on 2023-10-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_userwallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='transaction',
        ),
        migrations.AddField(
            model_name='userwallet',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('addition', 'Addition'), ('deduction', 'Deduction')], max_length=10, null=True),
        ),
    ]
