# Generated by Django 4.2.4 on 2023-10-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_remove_userwallet_transaction_userwallet_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('credited', 'Credited'), ('deduction', 'Deduction')], max_length=10, null=True),
        ),
    ]
