# Generated by Django 4.2.2 on 2023-08-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_subcategory_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
