# Generated by Django 4.2.4 on 2023-09-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0003_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='wallet_added',
            field=models.BooleanField(default=False),
        ),
    ]
