# Generated by Django 4.2.4 on 2023-10-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0006_remove_coupon_code_coupon_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(),
        ),
    ]
