# Generated by Django 4.2.2 on 2023-09-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0006_order_cancel_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('Accidently ordered', 'Accidently ordered'), ('No longer needed', 'No longer needed'), ('Delivery address changed', 'Delivery address changed'), ('Damaged product', 'Damaged product')], max_length=50, null=True),
        ),
    ]
