# Generated by Django 4.2.2 on 2023-09-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0007_alter_order_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.CharField(blank=True, choices=[('Damaged product', 'Damaged product'), ('Accidently ordered', 'Accidently ordered'), ('No longer needed', 'No longer needed'), ('Delivery address changed', 'Delivery address changed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('Accidently ordered', 'Accidently ordered'), ('No longer needed', 'No longer needed'), ('Delivery address changed', 'Delivery address changed')], max_length=100, null=True),
        ),
    ]
