# Generated by Django 4.2.4 on 2023-09-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
