# Generated by Django 4.2.4 on 2023-09-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0011_order_order_amount_order_wallet_amount_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_amount',
            new_name='order_grand_total',
        ),
    ]
