# Generated by Django 4.2.4 on 2023-09-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0012_rename_order_amount_order_order_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_grand_total',
        ),
    ]
