# Generated by Django 4.2.4 on 2023-10-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0015_alter_payment_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid_for_order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
