# Generated by Django 4.2.4 on 2023-10-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0016_order_amount_paid_for_order_alter_order_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
