# Generated by Django 4.2.2 on 2023-10-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0017_order_refund_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount_paid_for_order',
            new_name='payable_amount',
        ),
    ]
