# Generated by Django 4.2.2 on 2023-10-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0018_rename_amount_paid_for_order_order_payable_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_ordered',
            new_name='is_paid',
        ),
    ]
