# Generated by Django 4.2.4 on 2023-10-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0020_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
