# Generated by Django 4.2.4 on 2023-10-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0021_alter_invoice_issue_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
