# Generated by Django 4.2.4 on 2023-10-13 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0024_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='return_requested',
        ),
    ]
